#
# Kanban server Dockerfile
#
# https://github.com/
#

# Pull base image.
FROM debian:latest

MAINTAINER hihouhou < hihouhou@hihouhou.com >

# Update & install packages
RUN apt-get update && \
    apt-get install -y rsyslog unzip nginx wget php5-fpm php5-cli php5-sqlite 

# install kashboard
RUN cd / && \
wget http://kanboard.net/kanboard-latest.zip && \
unzip kanboard-latest.zip && \
chown -R www-data:www-data /kanboard && \
rm kanboard-latest.zip 

#add php configuration file
ADD php.ini /etc/php5/fpm/

#configure nginx
ADD nginx.conf /etc/nginx/
ADD fastcgi.conf /etc/nginx/
ADD kanboard /etc/nginx/sites-enabled/
#RUN rm /etc/nginx/sites-enable/default
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

#If no autogenerated
RUN mkdir /etc/nginx/ssl
ADD server.crt /etc/nginx/ssl/
ADD server.key /etc/nginx/ssl/
RUN chmod 400 /etc/nginx/ssl/*

EXPOSE 443

# startup
ADD start.sh /start.sh
RUN chmod 0755 /start.sh
CMD ["bash", "start.sh"]
#CMD service nginx start && service php5-fpm start
